[package]
name = "in-betweeners"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
counter = "0.6.0"
rayon = "1.10.0"
ordered-float = "4.5.0"
mockall = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[dev-dependencies]
approx = "0.5.1"
