[package]
name = "prog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "solutions_bench"
harness = false
