siteGenerator : siteGenerator.c
	gcc -Wall -g -O3 siteGenerator.c -o siteGenerator
masterGenerator : masterGenerator.c
	gcc -Wall -g masterGenerator.c -o masterGenerator
clean :
	$(RM) masterGenerator siteGenerator
