.PHONY: clean
mergeSort.o : mergeSort.c
	gcc -Wall -g $< -o $@
reverseLinkedList.o : reverseLinkedList.c
	gcc -Wall -g $< -o $@

maxSubSum.o : maxSubSum.c
	gcc -Wall -g $< -o $@

treeToLinkedDList.o : treeToDLinkedList.c
	gcc -Wall -g $< -o $@

reverseDoublyLinkedList.o : reverseDoublyLinkedList.c
	gcc -Wall -g $< -o $@
clean : 
	rm *.o
