[package]
name = "xkcd_parser"
version = "0.1.0"
authors = ["Will Koster <jameswk2@illinois.edu>"]
edition = "2024"

[dependencies]
curl = {git = "https://github.com/carllerche/curl-rust"}
regex = "0.1"
htmlescape = {git = "https://github.com/veddan/rust-htmlescape"}
